/**
 * Restore-preparation target database adapter — allow-listed source URL
 * parsing (reusing postgres-tools' validated parser), safe generated target
 * naming, and Prisma-boundary absence/creation checks for isolated restore
 * targets.
 *
 * Design "Confirmed isolated restore preparation": Prisma verifies
 * allowed host, non-live name, and absence before creation. Every target name
 * is either generated by this module (validated before use) or checked
 * against that same fixed pattern before any DDL runs.
 *
 * `MaintenanceClient` mirrors the PrismaClient raw-query methods actually
 * used here — a real `PrismaClient` satisfies it structurally. Unit tests
 * inject a fake at this same DB boundary (project convention: mock Prisma
 * only at its DB boundary); no real PostgreSQL connection is required.
 *
 * Spec: admin-database-backups — "Confirmed isolated restore preparation".
 * Design: "Storage and Safety", "Interfaces / Contracts".
 */
import { randomBytes } from "crypto";

import { BackupNotRestorableError } from "../errors/errors";

import { parsePostgresUrl } from "./postgres-tools";

const RESERVED_DATABASE_NAMES = new Set(["postgres", "template0", "template1"]);

// Matches ONLY names this module itself generates:
// mercado_restore_<UTC YYYYMMDDTHHMMSSZ>_<8 lowercase hex>
const GENERATED_NAME_PATTERN = /^mercado_restore_\d{8}T\d{6}Z_[0-9a-f]{8}$/;

const MAX_POSTGRES_IDENTIFIER_BYTES = 63;

export interface MaintenanceClient {
  $queryRawUnsafe<T = unknown>(query: string, ...values: unknown[]): Promise<T>;
  $executeRawUnsafe(query: string, ...values: unknown[]): Promise<number>;
}

// ---------------------------------------------------------------------------
// Safe target naming
// ---------------------------------------------------------------------------

/**
 * Generates a validated, collision-resistant restore target name:
 * `mercado_restore_<UTC:YYYYMMDDTHHMMSSZ>_<8 hex>` — well under the
 * 63-byte PostgreSQL identifier limit.
 */
export function generateTargetDatabaseName(now: Date = new Date()): string {
  const utc = now.toISOString().replace(/[-:]/g, "").replace(/\.\d+Z$/, "Z");
  const suffix = randomBytes(4).toString("hex");
  const name = `mercado_restore_${utc}_${suffix}`;
  assertSafeTargetName(name);
  return name;
}

/**
 * Rejects any name that is not one this module generates, that is a
 * reserved system database, or that collides with the live source database
 * (spec "Unsafe restore request": "invalid ... target ... MUST fail without
 * live-database mutation"). This is the single structural gate every target
 * name passes through before any query or DDL touches it.
 */
export function assertSafeTargetName(name: string, liveDatabaseName?: string): void {
  const byteLength = Buffer.byteLength(name, "utf8");
  if (byteLength === 0 || byteLength > MAX_POSTGRES_IDENTIFIER_BYTES) {
    throw new BackupNotRestorableError("Restore target name has an invalid length");
  }
  if (!GENERATED_NAME_PATTERN.test(name)) {
    throw new BackupNotRestorableError("Restore target name does not match the generated pattern");
  }
  if (RESERVED_DATABASE_NAMES.has(name.toLowerCase())) {
    throw new BackupNotRestorableError("Restore target name is a reserved system database");
  }
  if (liveDatabaseName && name.toLowerCase() === liveDatabaseName.toLowerCase()) {
    throw new BackupNotRestorableError("Restore target name matches the live source database");
  }
}

// ---------------------------------------------------------------------------
// Loopback-only maintenance connection
// ---------------------------------------------------------------------------

/**
 * Validates `sourceUrl` against loopback plus explicitly allowed hosts (via postgres-tools'
 * `parsePostgresUrl`) and returns the maintenance connection URL for the
 * `postgres` system database on the same host/port/credentials — the only
 * database Prisma may use to check absence and create the restore target.
 */
export function buildMaintenanceDatabaseUrl(
  sourceUrl: string,
  additionalAllowedHosts: readonly string[] = [],
): string {
  parsePostgresUrl(sourceUrl, additionalAllowedHosts);
  const maintenanceUrl = new URL(sourceUrl);
  maintenanceUrl.pathname = "/postgres";
  return maintenanceUrl.toString();
}

// ---------------------------------------------------------------------------
// Prisma DB-boundary checks
// ---------------------------------------------------------------------------

/** Throws `BackupNotRestorableError` (409) when `name` already exists. */
export async function assertTargetDatabaseAbsent(
  client: MaintenanceClient,
  name: string,
): Promise<void> {
  assertSafeTargetName(name);
  const rows = await client.$queryRawUnsafe<Array<{ exists: boolean }>>(
    "SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = $1) AS exists",
    name,
  );
  if (rows[0]?.exists) {
    throw new BackupNotRestorableError("Restore target database already exists");
  }
}

/**
 * Creates the validated, absent restore target database. `CREATE DATABASE`
 * does not support parameterized identifiers — `assertSafeTargetName` above
 * is the structural gate guaranteeing only a name matching
 * `GENERATED_NAME_PATTERN` ever reaches this string.
 */
export async function createTargetDatabase(client: MaintenanceClient, name: string): Promise<void> {
  assertSafeTargetName(name);
  await client.$executeRawUnsafe(`CREATE DATABASE "${name}"`);
}
