/**
 * Unit tests — target-database.ts (design threat matrix: unsafe restore
 * target rejection, loopback-only source URL parsing).
 *
 * Runtime harness: N/A for the Prisma DB boundary — a fake satisfying
 * `MaintenanceClient` is injected, per project convention (mock Prisma only
 * at its DB boundary). Real PostgreSQL coverage is deferred to the opt-in
 * real-PG integration test.
 *
 * Spec: admin-database-backups — "Confirmed isolated restore preparation".
 */
import { describe, expect, it, vi } from "vitest";

import { BackupNotRestorableError, BackupRuntimeUnavailableError } from "@/shared/errors/errors";
import {
  assertSafeTargetName,
  assertTargetDatabaseAbsent,
  buildMaintenanceDatabaseUrl,
  createTargetDatabase,
  generateTargetDatabaseName,
  type MaintenanceClient,
} from "@/shared/database-backups/target-database";

function fakeMaintenanceClient(exists: boolean): MaintenanceClient {
  return {
    $queryRawUnsafe: vi.fn().mockResolvedValue([{ exists }]),
    $executeRawUnsafe: vi.fn().mockResolvedValue(1),
  };
}

// ---------------------------------------------------------------------------
// Generated naming
// ---------------------------------------------------------------------------
describe("generateTargetDatabaseName", () => {
  it("generates a name matching mercado_restore_<UTC>_<8hex>, under 63 bytes", () => {
    const fixedNow = new Date("2026-08-17T21:11:06.123Z");
    const name = generateTargetDatabaseName(fixedNow);

    expect(name).toMatch(/^mercado_restore_20260817T211106Z_[0-9a-f]{8}$/);
    expect(Buffer.byteLength(name, "utf8")).toBeLessThanOrEqual(63);
  });

  it("generates a fresh name on each call", () => {
    const fixedNow = new Date("2026-08-17T21:11:06.123Z");
    const a = generateTargetDatabaseName(fixedNow);
    const b = generateTargetDatabaseName(fixedNow);
    expect(a).not.toBe(b);
  });
});

// ---------------------------------------------------------------------------
// RED — unsafe target name rejection
// ---------------------------------------------------------------------------
describe("assertSafeTargetName: RED unsafe-target coverage", () => {
  it.each([
    ["empty string", ""],
    ["overlong name", "a".repeat(64)],
    ["arbitrary operator-controlled name", "mercado_prod"],
    ["sql-injection-shaped name", `mercado_restore_20260817T211106Z_deadbeef"; DROP DATABASE mercado_prod; --`],
    ["reserved postgres", "postgres"],
    ["reserved template0", "template0"],
    ["reserved template1", "TEMPLATE1"],
    ["wrong prefix", "restore_20260817T211106Z_deadbeef"],
    ["missing hex suffix", "mercado_restore_20260817T211106Z_"],
  ])("rejects %s", (_label, unsafeName) => {
    expect(() => assertSafeTargetName(unsafeName)).toThrow(BackupNotRestorableError);
  });

  it("rejects a name matching the live source database", () => {
    const liveName = "mercado_restore_20260817T211106Z_deadbeef";
    expect(() => assertSafeTargetName(liveName, liveName)).toThrow(BackupNotRestorableError);
  });

  it("accepts a name generated by this module", () => {
    const name = generateTargetDatabaseName(new Date("2026-08-17T21:11:06.000Z"));
    expect(() => assertSafeTargetName(name, "mercado_prod")).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// RED — loopback-only maintenance URL (IPv4/IPv6 loopback coverage)
// ---------------------------------------------------------------------------
describe("buildMaintenanceDatabaseUrl: loopback coverage", () => {
  it("accepts an IPv4 loopback source and returns a /postgres maintenance URL", () => {
    const url = buildMaintenanceDatabaseUrl("postgres://u:p@127.0.0.1:5433/mercado_test");
    expect(new URL(url).pathname).toBe("/postgres");
    expect(new URL(url).hostname).toBe("127.0.0.1");
  });

  it("accepts an IPv6 loopback source and returns a /postgres maintenance URL", () => {
    const url = buildMaintenanceDatabaseUrl("postgres://u:p@[::1]:5432/mercado_dev");
    expect(new URL(url).pathname).toBe("/postgres");
  });

  it("accepts localhost", () => {
    const url = buildMaintenanceDatabaseUrl("postgres://u:p@localhost/mercado_dev");
    expect(new URL(url).pathname).toBe("/postgres");
  });

  it("rejects a non-loopback source host", () => {
    expect(() => buildMaintenanceDatabaseUrl("postgres://u:p@db.example.com/mercado")).toThrow(
      BackupRuntimeUnavailableError,
    );
  });
});

// ---------------------------------------------------------------------------
// Prisma DB-boundary checks (fake client — no real PostgreSQL connection)
// ---------------------------------------------------------------------------
describe("assertTargetDatabaseAbsent", () => {
  const name = "mercado_restore_20260817T211106Z_deadbeef";

  it("resolves when the target database does not exist", async () => {
    const client = fakeMaintenanceClient(false);
    await expect(assertTargetDatabaseAbsent(client, name)).resolves.toBeUndefined();
    expect(client.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining("pg_database"), name);
  });

  it("throws BackupNotRestorableError when the target database already exists", async () => {
    const client = fakeMaintenanceClient(true);
    await expect(assertTargetDatabaseAbsent(client, name)).rejects.toBeInstanceOf(
      BackupNotRestorableError,
    );
  });

  it("rejects an unsafe name before ever querying the client", async () => {
    const client = fakeMaintenanceClient(false);
    await expect(assertTargetDatabaseAbsent(client, "mercado_prod")).rejects.toBeInstanceOf(
      BackupNotRestorableError,
    );
    expect(client.$queryRawUnsafe).not.toHaveBeenCalled();
  });
});

describe("createTargetDatabase", () => {
  const name = "mercado_restore_20260817T211106Z_deadbeef";

  it("issues CREATE DATABASE with the validated, quoted name", async () => {
    const client = fakeMaintenanceClient(false);
    await createTargetDatabase(client, name);
    expect(client.$executeRawUnsafe).toHaveBeenCalledWith(`CREATE DATABASE "${name}"`);
  });

  it("rejects an unsafe name before ever executing DDL", async () => {
    const client = fakeMaintenanceClient(false);
    await expect(createTargetDatabase(client, "mercado_prod")).rejects.toBeInstanceOf(
      BackupNotRestorableError,
    );
    expect(client.$executeRawUnsafe).not.toHaveBeenCalled();
  });
});
